import type { FactKey } from "./types";

export const CLINICAL_KEYS: FactKey[] = [
  "clinical.primaryDiagnosis",
  "clinical.icd10Codes",
  "clinical.indication",
  "clinical.priorTreatments",
  "clinical.conservativeCareTried",
  "clinical.functionalImpact",
  "clinical.urgency",
  "clinical.procedureNarrative",
];

/** Keys the letter cannot be produced without, regardless of denial type. */
export const ALWAYS_REQUIRED: FactKey[] = [
  "claim.number",
  "claim.payerName",
  "claim.payerAppealAddress",
  "claim.dateOfService",
  "claim.billedAmount",
  "claim.deniedAmount",
  "claim.carcCodes",
  "claim.cptCodes",
  "patient.name",
  "patient.memberId",
  "patient.planType",
  "provider.name",
  "provider.npi",
  "provider.addressBlock",
  "provider.phone",
  "signer.name",
  "signer.title",
];

/** Human labels used inside placeholder tokens. */
export const FACT_LABELS: Record<FactKey, string> = {
  "claim.number": "Claim number",
  "claim.payerName": "Payer name",
  "claim.payerAppealAddress": "Payer appeal address",
  "claim.dateOfService": "Date of service",
  "claim.dateProcessed": "Date processed",
  "claim.billedAmount": "Billed amount",
  "claim.allowedAmount": "Allowed amount",
  "claim.paidAmount": "Paid amount",
  "claim.deniedAmount": "Denied amount",
  "claim.carcCodes": "CARC codes",
  "claim.rarcCodes": "RARC codes",
  "claim.cptCodes": "CPT codes",
  "claim.icd10Codes": "ICD-10 codes",
  "claim.modifiers": "Modifiers",
  "claim.timelyFilingDays": "Timely filing days",
  "claim.authorizationNumber": "Authorization number",
  "claim.goodCauseDescription": "Good cause description",
  "claim.appealAddressBlock": "Appeal address block",
  "patient.name": "Patient name",
  "patient.memberId": "Member ID",
  "patient.groupName": "Group name",
  "patient.groupNumber": "Group number",
  "patient.dateOfBirth": "Date of birth",
  "patient.planType": "Plan type",
  "provider.name": "Provider name",
  "provider.npi": "Provider NPI",
  "provider.tin": "Provider TIN",
  "provider.addressBlock": "Provider address",
  "provider.phone": "Provider phone",
  "provider.fax": "Provider fax",
  "signer.name": "Signer name",
  "signer.title": "Signer title",
  "signer.credentials": "Signer credentials",
  "signer.phone": "Signer phone",
  "clinical.primaryDiagnosis": "Primary diagnosis",
  "clinical.icd10Codes": "ICD-10 codes",
  "clinical.indication": "Clinical indication",
  "clinical.priorTreatments": "Prior treatments",
  "clinical.conservativeCareTried": "Conservative care tried",
  "clinical.functionalImpact": "Functional impact",
  "clinical.urgency": "Urgency",
  "clinical.procedureNarrative": "Procedure narrative",
  "appeal.level": "Appeal level",
  "appeal.deadline": "Appeal deadline",
  "appeal.authBranch": "Authorization status branch",
  "appeal.bundlingBranch": "Bundling basis branch",
  "appeal.timelyFilingBranch": "Timely filing basis branch",
  "appeal.claimDefectBranch": "Claim defect basis branch",
  "appeal.nonCoveredBranch": "Non-covered denial branch",
  "appeal.duplicateBranch": "Duplicate claim branch",
  "appeal.experimentalBranch": "Experimental denial branch",
  "appeal.wrongPayerBranch": "Wrong payer / COB branch",
};

export const DEFAULT_ENCLOSURES: ReadonlyArray<{ id: string; label: string }> = [
  { id: "operative_report", label: "Operative report" },
  { id: "office_notes", label: "Office/progress notes" },
  { id: "prior_auth", label: "Prior authorization approval or reference number" },
  { id: "medical_records", label: "Supporting medical records" },
  { id: "lmn", label: "Letter of medical necessity" },
  { id: "imaging", label: "Imaging reports" },
  { id: "corrected_claim", label: "Corrected claim (CMS-1500 / UB-04)" },
  { id: "timely_filing_proof", label: "Proof of timely submission" },
  { id: "eob_copy", label: "Copy of the EOB / remittance advice" },
];
